# Site settings
title: Purmirl
description: 'HeeGwon Cho / Infra Architect'
url: 'https://purmirl.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
#  name: 'purmirl'
  email: purmirl.petra@gmail.com
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username:  purmirl
  linkedin_username:  'heegwon-cho-820119147'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
